export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY_PROVIDER = 'USER_REPOSITORY_PROVIDER';
export const KONDO_REPOSITORY_PROVIDER = 'KONDO_REPOSITORY_PROVIDER';
export const MEDIA_REPOSITORY_PROVIDER = 'MEDIA_REPOSITORY_PROVIDER';